### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MaEdCo** [Klerith/node-intro-javascript#1]
` TODO MAL!
ReferenceError: Cannot access 'empleado' before initialization
    at D:\Manuel\async-await2.js:34:11
    at new Promise (<anonymous>)
    at getEmpleado (D:\Manuel\async-await2.js:30:12)
    at getInfoUsuario (D:\Manuel\async-await2.js:55:32)
    at Object.<anonymous> (D:\Manuel\async-await2.js:68:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)`
ese es el error que obtengo al ejecutar async-await

**Comment by MaEdCo** [comment]
Y otro error mas, no puedo usar el null check operator si es que entendi bien si asi se llama el ?.
``
PS D:\Manuel> node promesas    
D:\Manuel\promesas.js:32
        const empleado = empleados.find( e => e.id === id )?.nombre;
                                                            ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
``
